vector_database:
    embedding_model_name: "ViT-B-16"
    embedding_model_checkpoint: "openai"
    db_directory: "db"
    existing_text_db_directory: "data/databases/clip_textdb"
    existing_image_db_directory: "data/databases/image_db"
    image_collection_name: "Image_Store"
    text_collection_name: "Text_Store"
    is_remote: False
    url: None

agents:
    llm_name: "mixtral"
    temperature: 0.1

fastapi:
    host: "0.0.0.0"
    port: 8000
